project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "!lectures/05-testing/05-testing.qmd"

website:
  title: "Applied Econometrics (AECN 896-004)"
  open-graph: true # https://quarto.org/docs/websites/website-tools.html#open-graph
  page-footer: "Made with Quarto"
  # sidebar:
  #   style: "docked"
  #   search: true
  #   contents:
  #     - text: "Univariate Regression"
  #       href: lectures/01-univariate-introduction/univariate_regression_x.qmd
  navbar:
    right:
      - text: Syllabus
        href: syllabus.qmd
      # - text: Schedule
      #   href: schedule.qmd
      - text: Lecture Notes
        href: lectures/index.qmd
      - text: Lecture Notes (R Lab)
        href: LabLectures.qmd
      # - text: Slides
      #   menu:
      #     - text: 01 - Univariate Regression
      #       href: lectures/univariate/univariate_regression_x.rmd
format:
  html:
    theme: [cosmo, styles.scss]
