---
title: "Midterm I"
author: "Your Name Here"
execute:
  echo: true
---


# Instruction

+ In answering the questions, make sure you provide detailed explanations to justify your answers. Simply stating yes or no will not earn you any points. 

+ You have one and a half hour to finish the exam. Once you are done, please submit your assignment using [this Dropbox submission request link](https://www.dropbox.com/request/sX2gGwkxnlRLgTuMFZIc). Name your qmd file using the following convention: `lastname_midterm_1.qmd`. For example, it would be `Mieno_midterm_1.qmd` for me.

```{r library, include=FALSE, cache = F}
library(modelsummary)
library(tidyverse)
library(fixest)
```


# Problem 1

Your research team has ran an **randomized** experiment to obtain data for estimating the impact of fertilizer on corn yield.

## Question (1)

Another student of your team is thinking of estimating the following model.

$$
\begin{aligned}
Y = \beta_0 + \beta_1 F + v
\end{aligned}
$$

+ $Y$: corn yield (bu/acre)
+ $F$: fertilizer rate (lb/acre)
+ $v$: error term

Are you comfortable with the functional form specification? What is the functional relationship between $Y$ and `F` that is imposed in this model? Can you think of a model that reflects the true relationship between them in a more realistic way though not perfect? Explain.


## Question (2)

Now, suppose the linear model above is specified correctly. He is not sure about whether you have an endogeneity problem and the OLS estimation of $\beta_1$ is biased or not. What is your opinion? Explain. 

## Question (3)

He is also thinking of using another model shown below.

$$
\begin{aligned}
yield = \beta_0 + \beta_1 F + \beta_2 OM + v
\end{aligned}
$$

$OM$ stands for organic matter and $\beta_2$ is not zero (that is OM has an non-zero impact on corn yield). Do you prefer this model or the first model? Why? Explain. Discuss from the perspective of both bias in estimating $\beta_1$ and the variance of $\widehat{\beta_1}$.


# Problem 2

Your research team has collected observational (non-experimental) data on the nutrition status ($NS$) of children and household income ($HI$).

An undergraduate student of your team estimated the following model:

$$
\begin{aligned}
NS = \beta_0 + \beta_1 HI + v
\end{aligned}
$$

## Question (1)
Is her estimation of $\beta_1$ reliable (unbiased)? What is your opinion? 


## Question (2)

What other variables do you suggest including in the model if you observe them? 


## Question (3)

Suppose you suggested the following model to her instead of the one she suggested:

$$
\begin{aligned}
NS = \beta_0 + \beta_1 HI + \beta_2 FP + v
\end{aligned}
$$

, where $FP$ is the local food price index (the higher, the more expensive).

When she checked the correlation coefficient between $HI$ and $FP$, she found out that their correlation was $0.6$. She said that we should drop $FP$ because they are highly correlated. What is your opinion and what do you suggest to her? Explain.

# Problem 3

Your research team has collected data on education (observed in year) and income (observed in $1,000) among other variables and estiamted the following model.

$$
\begin{aligned}
Income = \beta_0 + \beta_1 log(Educ) + v
\end{aligned}
$$

The estimated model turned out to be as follows:

$$
\begin{aligned}
Income = 50 + 5 log(Educ) + v
\end{aligned}
$$

## Question (1)

How can you interpret the coefficient estimate on $log(Educ)$ of 5? 

## Question (2)

You noticed that `ability` is a very important variable influencing both `income` and `Educ`. What do you think is the direction of bias on $log(Educ)$ in the above model? Is $5$ likely to be over-stating or under-stating the real impact of `Educ`? Explain. 

# Problem 4

For these questions, you do not have to explain your answers.

## Question (1) 

Define homoskedasctic and heteroskedastic error

## Question (2) 

If error is heteroskedastic and you do not take that into account in estimating the coefficients and their standard errors, is the OLS coefficient estimation unbiased?

## Question (3)

State the difference in **estimator** and **estimate**. Then, answer the Yes/No question below

+ Does estimate have a variance?
+ Is estimator a random variable?
+ Can estimate be unbiased?