---
author: "Your Name Here"
format:
  html:
    number-sections: true
    number-depth: 1
    theme: flatly
    toc: true
execute:
  echo: true
  message: false
  warning: false
---


```{r setup_not_remove, echo=FALSE, include = F}
library(knitr)
library(here)
# opts_knit$set(root.dir = here("AssignmentsInstructor/Assignment_2"))
# setwd(here("AssignmentsInstructor/Assignment_2"))
opts_chunk$set(
  echo = TRUE,
  comment = NA,
  message = FALSE,
  warning = FALSE,
  tidy = FALSE,
  #--- figure related ---#
  fig.align = "center",
  fig.width = 5,
  fig.height = 4
  # dev='pdf'
)
```

# Instruction


Please submit your assignment (both the qmd and the resulting html files) using the following [Dropbox submission request link](https://www.dropbox.com/request/QoEGkBxBSn1xvmYhJbe1). Name your qmd file using the following convention: `lastname_assignment_2.qmd`. For example, it would be `Mieno_assignment_2.qmd` for me. 

I do not accept any hand-written answers (you will get score of zero for that problem). Leave all the R codes and results in your answer (where appropriate) for the computer exercises. If your R codes are not provided, you will get score of 0 for that question.

You are encouraged to discuss the problems with your classmates. However, I would recommend that you do so after you try all the problems yourself. You would be simply doing disservice to yourself if you resort to your friends' help immediately, depriving you of important opportunities to think carefully about what we have learned and understand them through solving the problems. 

------



<!-- Non-computer Exercises -->
# Non-computer Exercises

<!-- Problem 3 -->
## Problem 3 (Chapter 3)

The following model is a simplified version of the multiple regression model used by Biddle and Hamermesh (1990) to study the trade-off between time spent sleeping and working and to look at other factors affecting sleep:
$$sleep = \beta_0 + \beta_1 totwrk + \beta_2 educ + \beta_3 age + u$$
where $sleep$ and $totwrk$ (total work) are measured in minutes per week and $educ$ and $age$
are measured in years.

------

(i) If adults trade off sleep for work, what is the sign of $\beta_1$?


------

(ii) What signs do you think $\beta_2$ and $\beta_3$ will have?



------

(iii) Using the data in SLEEP75.RAW, the estimated equation is
$$\hat{sleep} = 3,638.25 -0.148 totwrk -11.13 educ + 2.20 age $$
$$ n=706, \;\; R^2=0.113$$
If someone works five more hours per week, by how many minutes is sleep predicted to fall? Is this a large trade-off?


------

(iv) Discuss the sign and magnitude of the estimated coefficient on $educ$.


------

(v) Would you say $totwrk$, $educ$, and $age$ explain much of the variation in $sleep$? What other factors might affect the time spent sleeping? Are these likely to be correlated
with $totwrk$? What happens to the coefficient estimator on $totwrk$ if the other factors are indeed correlated with $torwrk$?


------

<!-- Problem 7 -->
## Problem 7 (Chapter 3)

Which of the following can cause OLS estimators to be biased? Explain why or why not?

(i) Heteroskedasticity.
(ii) Omitting an important variable.
(iii) A sample correlation coefficient of .95 between two independent variables both included in the model.


------

## Problem 9 (Chapter 3)

The following equation describes the median housing price in a community in terms of amount of pollution ($nox$ for nitrous oxide) and the average number of rooms in houses in the community ($rooms$):

$$log(price)=\beta_0+\beta_1log(nox)+\beta_2 rooms+u$$

------

(i) What are the probable signs of $\beta_1$ and $\beta_2$? What is the interpretation of $\beta_1$? Explain.


------

(ii) Why might $nox$ [or more precisely, log($nox$)] and $rooms$ be negatively correlated? If this is the case, does the simple regression of log($price$) on log($nox$) produce an upward or a downward biased estimator of $\beta_1$? (Hint: look at the slides on the direction of omitted variable bias)


------

(iii) Using the data in HPRICE2.RAW, the following equations were estimated:
$$\hat{log(price)}=11.71-1.043log(nox) $$
$$\hat{log(price)}=9.23-0.718log(nox)+ 0.306 rooms$$
Is the relationship between the simple and multiple regression estimates of the elasticity of price with respect to $nox$ what you would have predicted, given your answer in part (ii)? Does this mean that $-0.718$ is definitely closer to the true elasticity than $-1.043$?


------

<!-- Computer Exercises -->

# Computer Exercises



## Problem C6 (Chapter 3)

Use the data set in **wage2.rds** for this problem. As usual, be sure all of the following regressions contain an intercept (Hint: this question is about omitted variable bias). 

------



------

(i) Run a simple regression of $IQ$ on $educ$ to obtain the slope coefficient, say, $\tilde{\sigma}_1$.


------

(ii) Run the simple regression of log($wage$) on $educ$, and obtain the slope coefficient, $\tilde{\beta}_1$.


------

(iii) Run the multiple regression of log($wage$) on $educ$ and $IQ$, and obtain the slope coefficients, $\hat{\beta}_1$ and $\hat{\beta}_2$, respectively.


------

(iv) Verify that $\tilde{\beta}_1=\hat{\beta}_1$ + $\hat{\beta}_2\tilde{\sigma}_1$.

------

(v) What does $\hat{\beta}_2\tilde{\sigma}_1$ represent?





## Problem C8 (Chapter 3)

Use the data in **discrim.dta** to answer this question (there are NAs in the data set, so remove them first). These are ZIP code–level data on prices for various items at fast-food restaurants, along with characteristics of the zip code population, in New Jersey and Pennsylvania. The idea is to see whether fast-food restaurants charge higher prices in areas with a larger concentration of blacks.

Here are the definitions of variables:

+ $prpblck$: proportion of black people
+ $income$: median income (in $\$$)
+ $lincome$: logged $income$
+ $psoda$: average price of soda (in $\$$)
+ $prppov$: proportion of people in poverty
+ $hseval$: median value of owner-occupied housing units (in $\$$)
+ $hseval$: logged $hseval$

--------



--------

(i) Find the average values of $prpblck$ and $income$ in the sample, along with their standard deviations. Use `dplyr::summarize()` function.



--------

(ii) Consider a model to explain the price of soda, $psoda$, in terms of the proportion of the population that is black and median income:
$$psoda=\beta_0+\beta_1 prpblck + \beta_2 income +u $$
Estimate this model by OLS and report the results, including the sample size and R-squared. Interpret the coefficient on $prpblck$. Do you think it is economically large?



<br>


--------

(iii) Compare the estimate from part (ii) with the simple regression estimate from $psoda$ on $prpblck$. Is the discrimination effect larger or smaller when you control for income?



<br>

--------

(iv) A model with a constant price elasticity with respect to income may be more appropriate. Report estimates of the model:
$$log(psoda)=\beta_0+\beta_1 prpblck + \beta_2 log(income) +u $$
If $prpblck$ increases by .20 (20 percentage points), what is the estimated percentage change in $psoda$?



<br>


--------

(v) Now add the variable $prppov$ to the regression in part (iv). What happens to $\beta_{prpblck}$?


<br>


--------

(vi) Find the correlation between log($income$) and $prppov$. Is it roughly what you expected?


<br>


--------

(vii) Evaluate the following statement: "Because log($income$) and $prppov$ are so highly correlated, they have no business being in the same regression."



------

## Problem C9 (Chapter 4)

Use the data in **discrim.dta** (you have imported this data already in the previous problem) to answer this question.

------

(i) Use OLS to estimate the model
$$log(psoda)=\beta_0+\beta_1 prpblck + \beta_2 log(income) + \beta_2 prppov + u $$
and report the results in the usual form. Is $\beta_1$ statistically different from zero at the $5\%$ level against a two-sided alternative? What about at the $1\%$ level?



------

(ii) What is the correlation between log($income$) and $prppov$ (use **cor()** function in R to find correlation coefficient)? Is each variable statistically significant at the $5\%$ level? Report the two-sided p-values.



------

(iii) To the regression in part (i), add the variable log($hseval$). Interpret its coefficient and report the two-sided $p$-value for $H_0$: $\beta_{log(hseval)}=0$


<br>



------

(iv) In the regression in part (iii), what happens to the individual statistical significance of log($income$) and $prppov$? Are these variables jointly significant? (Compute a p-value.) What do you make of your answers? Use `car::linearHypothesis()` to run the F-test.


<br>

------

(v) Given the results of the previous regressions, which one would you report as most reliable in determining whether the racial makeup of a zip code influences local fast-food prices?



