---
title: "Midterm I"
author: "Your Name Here"
execute:
  echo: true
---


# Instruction

+ In answering the questions, make sure you provide detailed explanations to justify your answers. Simply stating yes or no will not earn you any points. 

+ You have one and a half hour to finish the exam. Once you are done, please submit your assignment using [this Dropbox submission request link](https://www.dropbox.com/request/sX2gGwkxnlRLgTuMFZIc). Name your qmd file using the following convention: `lastname_midterm_1.qmd`. For example, it would be `Mieno_midterm_1.qmd` for me.

```{r library, include=FALSE, cache = F}
library(modelsummary)
library(tidyverse)
library(fixest)
```


# Problem 1

Your research team has ran an **randomized** experiment to obtain data for estimating the impact of fertilizer on corn yield.

## Question (1)

Another student of your team is thinking of estiamting the following model.

$$
\begin{aligned}
Y = \beta_0 + \beta_1 F + v
\end{aligned}
$$

+ $Y$: corn yield (bu/acre)
+ $F$: fertilizer rate (lb/acre)
+ $v$: error term

Are you comfortable with the functional form specification? What is the functional relationship between $Y$ and `F` that is imposed in this model? Can you think of a better model that reflects the true relationship between them in a more realistic way? Explain.

<span style = "color: blue;"> The marginal impact of fertilizer on corn yield declines as the amount of fertilizer increases. The current model, however, assumes that their relationshiop is completely linear, meaning the marginal impact of fertilizer on corn yield is constant. For example, linear-log model may better represent the actualy relationship beterrn corn yield and fertilizer. </span>


## Question (2)

Now, suppose the linear model above is specified correctly. He is not sure about whether you have an endogeneity problem and the OLS estimation of $\beta_1$ is biased or not. What is your opinion? Explain. 

<span style = "color: blue;"> You do not because the data is from a randomized experiment and fertilizer rate is not correlated with any variables including unobserved factors in the error term. </span>

## Question (3)

He is also thiking of using another model shown below.

$$
\begin{aligned}
yield = \beta_0 + \beta_1 F + \beta_2 OM + v
\end{aligned}
$$

$OM$ stands for organic matter and $\beta_2$ is not zero (that is OM has an non-zero impact on corn yield). Do you prefer this model or the first model? Why? Explain.

<span style = "color: blue;"> Yes. This is because including OM will reduce the size of the error term (by taking it out from the error term). Moreover, $OM$ is nor correlated with $F$. Therefore, including it is going to make the estimation of $\beta_1$ more accurate. </span>

# Problem 2

Your research team has collected observational (non-experimental) data on the nutrition status ($NS$) of childs and household income ($HI$).

An undergraduate student of your team estimated the following model:

$$
\begin{aligned}
NS = \beta_0 + \beta_1 HI + v
\end{aligned}
$$

## Question (1)
Is her estimation of $\beta_1$ reliable (unbiased)? What is your opinon? 

<span style = "color: blue;"> It is not because there are so many factors in the error term that can be correlated with HI, causing bias. </span>

## Question (2)

What other variables do you suggest including in the model? 

<span style = "color: blue;"> genetic traits, gender, diet, etc </span>

## Question (3)

Suppose you suggested the following model to her instead of the one she suggested:

$$
\begin{aligned}
NS = \beta_0 + \beta_1 HI + \beta_2 FP + v
\end{aligned}
$$

, where $FP$ is the local food price index (the higher, the more expensive).

When she checked the correlation coefficient between HS and FP, she found out that their correlation was $0.6$. She said that we should drop $FS$ because they are highly correlated. What is your opinion and what do you suggest to her? Explain.

<span style = "color: blue;"> Even though the correlation between HS and FP is 0.6, I would not suggest dropping FP as a variable from this regression model. If you were to make this a univariate regression model, leaving FS in the error term would likely create a biased estimator given that they are correlated. However, if the coefficient on FP is non-zero, which is likely the case, the variance will be greater than it would be in the univariate model. This depends on both the correlation between HS and FP and the magnitude of B2. Without knowing the value of the coefficient on FP, I would still suggest not dropping FP because econometricists prefer to have an unbiased estimation. </span>

# Problem 3

Your research team has collected data on education (observed in year) and income (observed in $1,000) among other variables and estiamted the following model.

$$
\begin{aligned}
Income = \beta_0 + \beta_1 log(Educ) + v
\end{aligned}
$$

The estimated model turned out to be as follows:

$$
\begin{aligned}
Income = 50 + 5 log(Educ) + v
\end{aligned}
$$

## Question (1)

How can you interpret the coefficient estimate on $log(Educ)$ of 5? 

<span style = "color: blue;"> If education increases by 1 percent, then the income increases by $50. </span>

## Question (2)

You noticed that `ability` is a very important variable influencing both `income` and `Educ`. What do you think is the direction of bias on $log(Educ)$ in the above model? Is $5$ likely to be over-stating or under-stating the real impact of `Educ`? Explain. 

<span style = "color: blue;">Ability is positively correlated with income and education. Therefore, not including ability would cause positive bias on the estimation of the impact of education.</span>

# Problem 4

For these questions, you do not have to expalin your answers.

## Question (1) 

Define homoskedasctic and heteroskedastic eror

## Question (2) 

If error is heteroskedastic and you do not take that into account in estiamting the coefficients and their standard errors, is the OLS coefficient estimation unbiased?

<span style = "color: blue;"> No, it does not. </span>

## Question (3)

State the difference in **estimator** and **estimate**. Then, answer the Yes/No question below

+ Does estimate have a variance? <span style = "color: blue;"> No </span>
+ Is estimator a randome variable? <span style = "color: blue;"> Yes </span>
+ Can estimate be unbiased? <span style = "color: blue;"> No </span>