---
title: "00-0: Logistics"
format: 
  revealjs: 
    theme: [default, ../custom.scss]
    fontsize: 1.4em
    callout-icon: false
    scrollable: true
    echo: true
    fig-dpi: 400
---

# Logistics

<html><div style='float:left'></div><hr color='#EB811B' size=1px width=1000px></html>

## Instructors

+ <span style = "color: red;"> Instructor </span>: Taro Mieno (Office: 209, E-mail: tmieno2@unl.edu)
+ <span style = "color: red;"> Teaching Assistant </span>: 
  - TBD

## Goals of the course
+ Learn modern introductory econometric theory
+ Apply econometric theories to real economic problems
+ Learn how to use statistical software (R) so you can conduct research independently (without technical help from your advisor)
  - manage data
  - visualize data
  - run regressions
  - interpret results

## Text Books

**Recommended:** 
Wooldridge, Jeffrey M. 2006. "Introductory Econometrics: A Modern Approach (<span style = "color: red;">5</span>th edition)." Mason, OH: Thomson/South-Western.

## Course Schedule

+ Lectures (MW): 3:00-4:30pm
+ Lab sessions (F): 1:00-2:30pm

## Grading

+ Problem sets (3 assignments): 30% 
+ Small-size midterms  (2): 40% 
+ Paper: 40%


## Assignments
  
**Problem sets** 
+ Most questions are from the required text book
+ Some questions come from what we cover in lab sessions

** Quarto to do and submit your problem sets**
+ You are required to present your R codes
+ You learn how to compile your assignment with your R code written in a document using <span style = "color: red;"> Quarto </span>, which will be covered in the second lab session

**Caution** 
+ 2nd year students have answers to all the questions I will assign (I will use exactly the same problems because they are really good to learn econometrics)
+ You are free to copy and paste (or rephrase) the answers for your assignment. I won't bother to try to tell if you have copied and pasted answers.
+ However, you are simply doing dis-service to yourself by depriving yourself of learning opportunities
+ Moreover, your lack of understanding of the material will be clearly manifested on your performance at midterms and final paper

## Midterms

In-class open-book midterms

+ Midterm 1: Oct, 9 (M)
+ Midterm 2: Nov, 20 (M)


## Final Paper

In this assignment,
  + you write a paper with a particular emphasis on econometric analysis using a real world data set
  + you are encouraged to use the data set you are using for your masters thesis (talk with your advisor)
  + you need to ensure that you use a <span style = "color: red;"> panel </span> dataset
  + No presentation of your final paper

**Time line**

+ <span style = "color: red;"> Oct, 16 </span>: identify a research topic and the data set you will be using, and get an approval from the instructor
+ <span style = "color: red;"> Oct, 23 </span>: paper proposal 
+ <span style = "color: red;"> Dec, 15 </span>: final paper 

## Paper Proposal

**Introduction** 
+ clear identification of what you are trying to find out (research question) 
+ why the research question is worthwhile answering 

**Simple Model** 
+ dependent variable (the variable to be explained)
+ explanatory variable (variables to be explain)

**Data Source** 
+ where you get data

## Final Paper

**Introduction** 

+ clear identification of what you are trying to find out (research question) [1 point]
+ why the research question is worthwhile answering [1 point]

**Data description**

+ the nature of the data with summary statistics table [1 point]
+ visualize a few key variables in a meaningful way [3 points]

**Econometric Methods** 

The <span style = "color: red;"> process </span> of how you end up with the final econometric models and methods. [40 points (<span style = "color: red;"> or more </span>)]

+ justification of your choice of independent variables
+ potential endogeneity problems
+ what did you do to address the endogeneity problems?
+ justification of econometric model(s) and method(s)
+ identify appropriate standard error estimation methods

**Results, Discussions, and Conclusions**
+ interpret and describe the results [2 points]
+ implications of the results [1 point]
+ conclusions [1 point]

