---
title: "Assignment 1 (<span style='color:blue'>Score: /10 </span>)"
author: "Your Name Here"
format:
  html:
    number-sections: true
    number-depth: 1
    theme: flatly
    toc: true
execute:
  echo: true
  message: false
  warning: false
---

```{r setup_not_remove, echo=FALSE, include = F}
library(knitr)

# setwd(here("AssignmentsInstructor/Assignment_1"))
opts_chunk$set(
  echo = TRUE,
  comment = NA,
  message = FALSE,
  warning = FALSE,
  tidy = FALSE,
  #--- figure related ---#
  fig.align = "center",
  fig.width = 5,
  fig.height = 4
  # dev='pdf'
)
```

# Instruction

Due date is <span style='color:blue'>October, 11th </span> <span style='color:red'>before</span> the lab session on that day, in which this assignment is reviewed by the TA. Submission after the deadline would result in a heavy discount on the score. 

Please submit your assignment (both the qmd and the resulting html files) using the following [Dropbox submission request link](https://www.dropbox.com/request/QoEGkBxBSn1xvmYhJbe1). Name your qmd file using the following convention: `lastname_assignment_1.qmd`. For example, it would be `Mieno_assignment_1.qmd` for me. 

I do not accept any hand-written answers (you will get score of zero for that problem). Leave all the R codes and results in your answer (where appropriate) for the computer exercises. If your R codes are not provided, you will get score of 0 for that question.

You are encouraged to discuss the problems with your classmates. However, I would recommend that you do so after you try all the problems yourself. You would be simply doing disservice to yourself if you resort to your friends' help immediately, depriving you of important opportunities to think carefully about what we have learned and understand them through solving the problems. 

<!-- <span style="background:yellow">(you may remove this part when you submit your work)</span>  -->
<!-- Instruciton ends here -->

------

<!-- Non-computer Exercises --> 
# Non-computer Exercises

## Problem 1 

Let `kids` denote the number of children ever born to a woman, and let `educ` denote years of education for the woman. A simple model relating fertility to years of education is
$$
kids=\beta_0+\beta_1 educ+u
$$
where $u$ is the unobserved error.

------

(i) What kinds of factors are contained in $u$? Are these likely to be correlated with level of education?


------

(ii) Will a simple regression analysis uncover the ceteris paribus effect of education on fertility? Explain.



## Problem 6

Using data from 1988 for houses sold in Andover, Massachusetts, from Kiel and McClain (1995), the following equation relates housing price (`price`) to the distance from a recently built garbage incinerator (`dist`):
$$
\begin{aligned}
\widehat{log(price)} = 9.40 + 0.312\times log(dist)\\
n=135,\;\; R^2 = 0.162
\end{aligned}
$$

------

(i) Interpret the coefficient on $log(dist)$. Is the sign of this estimate what you expect it to be?


------

(ii) Do you think simple regression provides an unbiased estimator of the ceteris paribus elasticity of price with respect to dist? (Think about the city's decision on where to put the incinerator.)


------

(iii) What other factors about a house affect its price? Might these be correlated with distance from the incinerator?



<!-- Computer Exercises --> 

# Computer Exercises



## Problem C1

The data in __401K.csv__ are a subset of data analyzed by Papke (1995) to study the relationship between participation in a 401(k) pension plan and the generosity of the plan. The variable `prate` is the percentage of eligible workers with an active account; this is the variable we would like to explain. The measure of generosity is the plan match rate, `mrate`. This variable gives the average amount the firm contributes to each worker's plan for each $1 contribution by the worker. For example, if $mrate= 0.50$, then a $1 contribution by the worker is matched by a $50$ cents contribution by the firm.


------

(i) Find the average participation rate and the average match rate in the sample of plans.



------

(ii) Now, estimate the simple regression equation
$$
\hat{prate}=\hat{\beta}_0+\hat{\beta}_1\cdot mrate
$$
and present the results using the `msummary()` function from the `modelsummary` package.



<br>

------

(iii) Interpret the intercept in your equation. Interpret the coefficient on mrate.


------

(iv) Find the predicted prate when $mrate=3.5$. Is this a reasonable prediction? 
Explain what is happening here.





------

(v) How much of the variation in prate is explained by `mrate`? Is this a lot in your opinion?




## Problem C2

The data set in __CEOSAL2.dta__ contains information on chief executive officers for U.S. corporations. The variable `salary` is annual compensation, in thousands of dollars, and `ceoten` is prior number of years as company CEO.


------

(i) Find the average salary and the average tenure in the sample. 



------

(ii) How many CEOs are in their first year as CEO (that is, ceoten 5 0)? What is the longest tenure as a CEO? [Hint: use the `filter()` and `nrow()` functions]





------

(iii) Estimate the simple regression model
$$
log(salary)=\beta_0+\beta_1\cdot ceoten +u
$$
and report your results in the usual form using the `msummary()` function. What is the (approximate) predicted percentage increase in salary given one more year as a CEO?



<br>


------

## Problem C8
To complete this exercise you need a software package that allows you to generate data from the uniform and normal distributions.



(i) Start by generating $500$ observations $x_i$ – the explanatory variable – from the uniform distribution with range $[0,10]$. (Most statistical packages have a command for the Uniform[0,1] distribution; just multiply those observations by 10.) What are the sample mean and sample standard deviation of the $x_i$?


------

(ii) Randomly generate $500$ errors, $u_i$, from the Normal[0,36] distribution. (If you generate a Normal[0,1], as is commonly available, simply multiply the outcomes by six.) Is the sample average of the $u_i$ exactly zero? Why or why not? What is the sample standard deviation of the $u_i$?



------

(iii) Now generate the $y_i$ as
$$
y_i=1+2x_i+u_i 
$$
that is, the population intercept is one and the population slope is two. Use the data to run the regression of $y_i$ on $x_i$. What are your estimates of the intercept and slope? Are they equal to the population values in the above equation? Explain.


<br>


------

(iv) Obtain the OLS residuals, $\hat{u}_i$, and verify that the following equations hold (subject to rounding error).

```{=tex}
\begin{align}
\sum_{i=1}^n \widehat{u}_i = 0 \\
\sum_{i=1}^n \widehat{u}_i \cdot x_i = 0 
\end{align}
```







------

(v) Compute the same quantities of the equations in the question above, but use the errors $u_i$ in place of the residuals. Now what do you conclude? $\sum_{i=1}^n u_i=0$?






------

(vi) Repeat parts (i), (ii), and (iii) with a new sample of data, starting with generating the $x_i$. Now what do you obtain for $\hat{\beta}_0$ and $\hat{\beta}_1$? Why are these different from what you obtained in part (iii)?



